# Generated by the `homebrew` job in .github/workflows/ci.yml on every tag.
# Edit this template, not the copy in d3lph1/homebrew-tap — that one is
# overwritten by the next release.
class McpAtlassian < Formula
  desc "Lightweight MCP server for Jira and Confluence"
  homepage "https://github.com/d3lph1/mcp-atlassian"
  license "MIT"

  # The release ships bare binaries rather than archives, one per target;
  # each is the static build CI produced natively for that platform.
  on_macos do
    on_arm do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v0.1.3/mcp-atlassian-aarch64-apple-darwin"
      sha256 "b59075393b768154de87c8592f8d8377c61cdbe0b4c31e901339bcd3ffa27577"
    end
    on_intel do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v0.1.3/mcp-atlassian-x86_64-apple-darwin"
      sha256 "5c0083e1e05aad30b273a66d2269a3b376451f3d013f34ac518969f416c21cb1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v0.1.3/mcp-atlassian-aarch64-unknown-linux-musl"
      sha256 "b487d1d8d012e29d646dc4361591c280a747e17898d5cdbeac0617cf2fb9a14f"
    end
    on_intel do
      url "https://github.com/d3lph1/mcp-atlassian/releases/download/v0.1.3/mcp-atlassian-x86_64-unknown-linux-musl"
      sha256 "cc266c94d0b0c6132911c9992bdab9b23754788e807f6f0ee525bc7260078fa1"
    end
  end

  def install
    bin.install Dir["mcp-atlassian-*"].first => "mcp-atlassian"
  end

  test do
    assert_match "mcp-atlassian #{version}", shell_output("#{bin}/mcp-atlassian --version")
    # Refuses to start unconfigured, and says which variables it wants.
    output = shell_output("#{bin}/mcp-atlassian 2>&1", 1)
    assert_match "JIRA_URL", output
  end
end
